export default{
	name:"topics",
	data:[
		{
			name:"北邮人",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=Q0orpqOd8B"
		},
		{
			name:"微信",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=WnBe01o371"
		},
		{
			name:"微博",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=KqndgxeLl9"
		},
		{
			name:"36氪",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=Q1Vd5Ko85R"
		},
		{
			name:"虎嗅网",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=5VaobgvAj1"
		},
		{
			name:"IT之家",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=74Kvx59dkx"
		},
		{
			name:"哔哩哔哩",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=74KvxwokxM"
		},
		{
			name:"抖音",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=DpQvNABoNE"
		},
		{
			name:"煎蛋",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=NRrvWq3e5z"
		},
		{
			name:"北大未名",
			url:"https://api.codelife.cc/api/top/list?lang=cn&id=WnBe0z1v37"
		}
	]
}